### ISSUE TITLE
separar os calculos da planilha em funções

### ISSUE THREAD

**Issue by diogaumbueno** [HBN3tw0rk/automatiza-relatorio#3]

**Comment by GregMasterBr** [comment]
Essa PR resolveu essa issue
[https://github.com/HBN3tw0rk/automatiza-relatorio/pull/11](https://github.com/HBN3tw0rk/automatiza-relatorio/pull/11)

**Comment by GregMasterBr** [comment]
Essa PR resolveu essa issue
[https://github.com/HBN3tw0rk/automatiza-relatorio/pull/11](https://github.com/HBN3tw0rk/automatiza-relatorio/pull/11)
